### ISSUE TITLE
Cann't speciry trait option of InstructionArgs

### ISSUE THREAD

**Issue by aoikurokawa** [codama-idl/codama#339]
Related to #134, I have some accounts and types which include `f64` type which does not implement `Eq`, `PartialEq`.
So I declared the traitOption like this:
```
const traitOptions = {
	baseDefaults: [
		'borsh::BorshSerialize',
		'borsh::BorshDeserialize',
		'serde::Serialize',
		'serde::Deserialize',
		'Clone',
		'Debug',
	],
	dataEnumDefaults: [],
	scalarEnumDefaults: ['Copy', 'Hash', 'num_derive::FromPrimitive'],
	structDefaults: [],
};
```

Account and Types has changed, however, I could not change the derive trait of InstructionArgs. Is there any way to handle this issue?

Version:
```
"@codama/nodes-from-anchor": "^1.0.1",
"@codama/renderers": "^1.0.4",
"codama": "^1.1.0"
```

**Comment by lorisleiva** [comment]
Hey 👋 Well spotted, thanks for raising this! I can see the `instructionPage.njk` template is using hardcoded traits instead of using the new trait options. I've added this to my list of things to do. Bear with me. 😅

**Comment by lorisleiva** [comment]
Hi @aoikurokawa, sorry for the delay coming back to you. This is now published so everything should works as expected on your side. Please let me know if it doesn't. 🙏

**Comment by aoikurokawa** [comment]
Thank you so much!
